### ISSUE TITLE
Hallo

### ISSUE THREAD

**Issue by HermesTr** [milahu/alchi#2]
Würdest mir bitte etwas auf die Sprünge helfen. Flugblatt ist etwas zu kompliziert

**Comment by milahu** [comment]
moin hermes

wo soll ich anfangen?

**Comment by milahu** [comment]
das haupt-thema ist "menschen und ihre beziehungen"

wikipedia: https://en.wikipedia.org/wiki/Interpersonal_compatibility

auto übersetzung: https://translate.google.com/translate?sl=en&tl=de&u=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FInterpersonal_compatibility

meine arbeit soll dieses problem lösen:
> no general theory of interpersonal compatibility has been proposed in psychology

.. also eine allgemein-gültige theorie bieten, die alle beziehungen zu anderen typen korrekt vorhersagt, vorausgesetzt man geht vom richtigen menschentyp aus - vor allem: welches element wird verkörpert

**Comment by HermesTr** [comment]
Verstehe, finde ich sehr interessant.! Das mit Hausnummern und Nachbarschaft komme einfach ￼￼￼nicht da hinter. Könntest du mir das bezüglich ein Tip geben?.

**Comment by milahu** [comment]
> Das mit Hausnummern und Nachbarschaft

du meinst den teil

https://github.com/milahu/alchi/blob/b2db38c1a399a41e61ea8b1c44283d1498db97f1/deutsch/alchi-flyer.html#L716-L793

vor allem

> Das ist unser Minimal-Konsens
> als Grundlage für Selbstorganisation.

hier wird vorgeschlagen ein [peer discovery protocol](https://en.wikipedia.org/wiki/Local_Peer_Discovery) für menschen
also eine strategie, um beziehungen aufzubauen mit nachbarn
denen man sonst (zufällig) nicht "über den weg läuft"

problem: jeder hat seinen eigenen zeitplan (asynchron, unabhängig)
und man hat keine gemeinsamen termine (nebeneinander leben)

kriterien für einen treffpunkt

1. muss auch 100% offline funktionieren, ohne technik, ohne internet
2. muss dezentral sein
   1. jeder soll sich dort gleich "fremd" fühlen  
es soll also kein stammplatz sein, der schon von einer gruppe besetzt wird  
wo die gruppe entscheidet, wer bleiben darf und wer gehen muss
   2. wenn ein treffpunkt doch mal besetzt wird  
dann gibts noch genug andere treffpunkt zum ausweichen
3. muss zu jeder jahreszeit funktionieren
4. muss einfach zu merken sein


> **Club 16**: Wir treffen uns **jeden Tag** um 16 Uhr
> an den Hausnummern "K Mal 16"
> in den Straßen unserer Nachbarschaft.

das ist der minimal-konsens
um nachbarn zu treffen, die komplett fremd sind

K ist die abkürzung für 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, ....
also "die menge der natürlichen zahlen inklusive null"
"K Mal 16" ist dann (in [javascript](https://en.wikipedia.org/wiki/ECMAScript))

> $ node
> \> [Array.from({length:101}).map((_, K) => K * 16).join(', ')+', ....'](https://repl.it/@milahu/alchi-k-mal-16)
'0, 16, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 208, 224, 240, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024, 1040, 1056, 1072, 1088, 1104, 1120, 1136, 1152, 1168, 1184, 1200, 1216, 1232, 1248, 1264, 1280, 1296, 1312, 1328, 1344, 1360, 1376, 1392, 1408, 1424, 1440, 1456, 1472, 1488, 1504, 1520, 1536, 1552, 1568, 1584, 1600, ....'

wenn man schon nachbarn kennt
dann kann man mit denen auch andere treffpunkte ausmachen
zb wenn man um 16 uhr (haupt-treffpunkt) keine zeit hat
dann macht man einen neben-treffpunkt um 18 uhr
möglichst **jeden tag** zur gleichen zeit
(naturordnung kennt nur tag und nacht, keine wochen oder feiertage)

der 16 uhr treffpunkt bleibt der haupt-treffpunkt
zu dem immer wieder "abgesandte" geschickt werden
um immer wieder neue nachbarn treffen zu können
= einstiegspunkt für neue mitglieder

diese treffpunkte sind dann eine möglichkeit
die theorie (menschen und beziehungen)
in die wirklichkeit zu übersetzen
also um "passende beziehungen" aufzubauen

der aufbau von selbstorganisation hat mehrere phasen (zeitstufen)

1. flugblätter verteilen. diese werden zu 95% bis 99% ignoriert und weggeschmissen. diese arbeit braucht sehr viel geduld  
fixkosten: [200 eur pro drucker](https://geizhals.de/canon-pixma-g5050-3112c006-a2036002.html) (Canon Pixma G5050: 250 blatt, duplex)  
laufende kosten: [1 cent pro flugblatt](https://www.druckkosten.de/kosten.php?f%5Btyp_fs%5D=F&f%5Btyp_fn%5D=D&f%5Btyp_te%5D=_T&f%5B_a%5D=aktuell&f%5B_f%5D=%25&doc=6&set%5Btpages%5D=20000)  
pro tag kann man circa 500 blätter verteilen
2. nur ein prozent wird den zettel [lesen, verstehen und anwenden](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop)  
also jeden tag zu einem der 16 uhr treffpunkte kommen  
mit diesen [early adopters](https://de.wikipedia.org/wiki/Early_Adopter) kann man dann die theorie ausprobieren, also die fragen stellen "was ist mein element?" und "wer sind meine freunde?"  
wenn man damit erste erfolge gemacht hat, also wenn die "alchi formel" wirklich funktioniert, um kompatible beziehungen vorherzusagen .... 
3. .... dann können die early-adopters sicherer und ["aggressiver" auftreten](https://www.youtube.com/watch?v=CkY84-8R4BU), und [auf mission gehen](https://de.wikipedia.org/wiki/Missionar), also nicht nur flugblätter verteilen, sondern ihre nachbarn direkter ansprechen, zum beispiel "hausieren gehen". zitat: >>Wir gehen von Haus zu Haus, von Tür zu Tür und wir sagen "Hey! Wir suchen Freunde." (Der Rest ergibt sich dann irgendwie ....)"<<

> [Bettelmönche](https://wiki.yoga-vidya.de/Bettler#Bettelm.C3.B6nche)
>
> Und es gab auch immer wieder Bettler als spirituelle Menschen [schlaue bettler]. Wir finden zum Beispiel die Tradition der Bettelmönche. Wir finden das im Mittelalter, wo Mönche **von Haus zu Haus gegangen** sind, zum Beispiel Die Franziskaner waren eine Tradition von Bettelmönchen.

die monopolisten (kirche, staat, imperium, mainstream, fremdherrscher)
wehren sich gegen solche konkurrenz
und sagen "betteln und hausieren verboten"
(hängt als schild an manchen haustüren)

auch "kuppelei" im sinn von "arrangierte freundschaft"
hat bei uns irgendwie einen schlechten ruf

dazu passt der spruch:
große imperien bauen auf schwache völker
kann man schon machen, aber ist langristig extrem destruktiv
siehe globale zerstörung und die völlige ohnmacht der alten herren
von denen man eigentlich erwarten könnte
dass sie genug geld (also einfluss) haben, um diese probleme zu lösen
.... haben sie aber nicht, weil geld ist ein schlechtes argument für "einfluss"

siehe mein part zu "stärke und schlauheit"

https://github.com/milahu/alchi/blob/b2db38c1a399a41e61ea8b1c44283d1498db97f1/deutsch/alchi-flyer.html#L472-L520

aber ein imperium
das solche reform-bewegungen [mit gewalt unterdrückt](https://de.wikipedia.org/wiki/Protestantismus)
oder [missbraucht für kommerz](https://youtu.be/ykRIO0ovgH4?t=238)
so ein imperium [schaufelt damit nur sein eigenes grab](https://www.google.com/search?q=cartoon+sawing+the+branch+you+are+sitting+on&tbm=isch)

^ noch mehr [TLDR](https://www.urbandictionary.com/define.php?term=tl%3Bdr) für das schwach-gemachte volk : /

aber die kenntnis einer potenziellen lösung
[verpflichtet](https://de.wikipedia.org/wiki/Berufung_(Religion)) zu ihrer veröffentlichung ....

noch fragen?

**Comment by HermesTr** [comment]
Alles gut dann mal schauen ob ich jemanden finde..

**Comment by milahu** [comment]
@HermesTr noch da?

hier mein neuester versuch ... https://milahu.github.io/whoaremyfriends/whoaremyfriends.html

darfst jeden damit langweilen, der sich interessiert für psychologie, ecovillages, ...
